version: '3'

tasks:
  build-push:
    cmds:
      - docker buildx build . --platform linux/amd64,linux/arm64 -t ghcr.io/lausequites/php-container:php8.4 --push
  ghcr:login:
    cmds:
      - docker login ghcr.io -u lausequites